name: Deploy

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install pnpm
        run: npm i -g pnpm@~9
      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/.vitepress/dist
          cname: api-typing.yinzhenyu-su.com # if wanna deploy to custom domain
